# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Memories from an Platform Architect
email: victor.fondevilla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here I'll blog about random stuff like DevOps, Infrastructure, AWS, Kubernetes, NSX-T, VMware vSphere, Openstack...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.victorfondevilla.com" # the base hostname & protocol for your site
twitter_username: vFondevilla
github_username:  vFondevilla
clarity_header_iconshape: dna
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-mentions
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-avatar

# Build settings
markdown: kramdown

exclude: ['node_modules','package.json','.settings','.project','about_english.md','404.md']
compress_html:
  blanklines: true

sass:
  style: :expanded # You might prefer to minify using :compressed